[build]
  command = "npm run build"
  publish = "build"
  functions = "netlify/functions"

[dev]
  command = "npm start"
  functions = "netlify/functions"
  publish = "public"
  port = 8888
  targetPort = 3000
  autoLaunch = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200